version: '3.1'

services:

  postgresql:
    image: postgres:12.2
    restart: on-failure
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: devapp
    ports:
      - 5432:5432
